/ *****************************************************************************
/ *                    SSI DATA                                               *
/ *****************************************************************************
/ *                    Signals Identities File (SIG)                          *
/ *****************************************************************************
/ *    SCHEME NAME                 *   Coq Junction
/ *                                *
/ *    INTERLOCKING NAME           *   COQ_JUNCTION
/ *                                *
/ *    FILE NAME                   *   COQ.SIG
/ *                                *
/ *    VERSION                     *   1
/ *                                *
/ *    LAST CHECKED IN             *   Date: 14/09/23
/ *                                *
/ *    LAST CHANGED BY             *   Alexei Iliasov
/ *                                *


	S100	S101 	S102 	S103	S104
	S105	S106	S108	S110

